In [22]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/susan/Downloads/assessment_melb vserve.xlsx.csv")

In [23]:
df.head()

,suburb,address,rooms,type,price,method,sellerg,date,distance,postcode,...,bathroom,car,landsize,buildingArea,yearBuilt,councilArea,latitude,longitude,regionname,propertycount
0,Abbotsford,85 Turner St,2,h,1480000,S,Biggin,2016-12-03,2.5,3067,...,1,1.0,202,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019
1,Abbotsford,25 Bloomburg St,2,h,1035000,S,Biggin,2016-02-04,2.5,3067,...,1,0.0,156,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019
2,Abbotsford,5 Charles St,3,h,1465000,SP,Biggin,2017-03-04,2.5,3067,...,2,0.0,134,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019
3,Abbotsford,40 Federation La,3,h,850000,PI,Biggin,2017-03-04,2.5,3067,...,2,1.0,94,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019
4,Abbotsford,55a Park St,4,h,1600000,VB,Nelson,2016-06-04,2.5,3067,...,1,2.0,120,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019

In [24]:
df['price_per_room'] = df['price'] / df['rooms']

In [25]:
df['price_per_land'] = df['price'] / df['landsize'].replace(0, np.nan)

In [26]:
df['property_age'] = 2017 - df['yearBuilt']

In [27]:
df['yearBuilt'] = df['yearBuilt'].fillna(df['yearBuilt'].median())
df['property_age'] = 2017 - df['yearBuilt']

In [28]:
df[['price_per_room', 'price_per_land', 'property_age']].head()

   price_per_room  price_per_land  property_age
0   740000.000000     7326.732673          47.0
1   517500.000000     6634.615385         117.0
2   488333.333333    10932.835821         117.0
3   283333.333333     9042.553191          47.0
4   400000.000000    13333.333333           3.0

Task 2: Feature Engineering

New features were created to enhance property-level analysis:

• Price per Room: Calculated as price / rooms to evaluate cost efficiency of each property
• Price per Land Square Meter: Calculated as price / landsize to understand land value contribution
• Property Age: Calculated as 2017 - yearbuilt to estimate property lifecycle

Missing values in yearbuilt were filled using median before calculating property age to avoid null values.

These engineered features improve comparability and provide deeper insights into property valuation.