In [24]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/susan/Downloads/assessment_melb vserve.xlsx.csv")

In [25]:
df.head()

,suburb,address,rooms,type,price,method,sellerg,date,distance,postcode,...,bathroom,car,landsize,buildingArea,yearBuilt,councilArea,latitude,longitude,regionname,propertycount
0,Abbotsford,85 Turner St,2,h,1480000,S,Biggin,2016-12-03,2.5,3067,...,1,1.0,202,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019
1,Abbotsford,25 Bloomburg St,2,h,1035000,S,Biggin,2016-02-04,2.5,3067,...,1,0.0,156,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019
2,Abbotsford,5 Charles St,3,h,1465000,SP,Biggin,2017-03-04,2.5,3067,...,2,0.0,134,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019
3,Abbotsford,40 Federation La,3,h,850000,PI,Biggin,2017-03-04,2.5,3067,...,2,1.0,94,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019
4,Abbotsford,55a Park St,4,h,1600000,VB,Nelson,2016-06-04,2.5,3067,...,1,2.0,120,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019

In [26]:
df['buildingArea'] = df['buildingArea'].fillna(df['buildingArea'].median())

In [27]:
suburb_df = df.groupby('suburb').agg({
    'price': 'mean',
    'buildingArea': 'mean'
}).reset_index()

In [28]:
suburb_df['price_building_ratio'] = suburb_df['price'] / suburb_df['buildingArea']

In [29]:
suburb_df = suburb_df.sort_values(by='price_building_ratio', ascending=False)

In [30]:
suburb_df.head()

          suburb         price  buildingArea  price_building_ratio
195  Middle Park  2.082529e+06    133.352941          15616.674019
4    Albert Park  1.941355e+06    124.760870          15560.608701
60    Canterbury  2.180241e+06    177.088889          12311.561467
187     McKinnon  1.500000e+06    122.250000          12269.938650
41      Brighton  1.930158e+06    158.701338          12162.203685

In [31]:
suburb_df.round(2).head()

          suburb       price  buildingArea  price_building_ratio
195  Middle Park  2082529.41        133.35              15616.67
4    Albert Park  1941355.07        124.76              15560.61
60    Canterbury  2180240.74        177.09              12311.56
187     McKinnon  1500000.00        122.25              12269.94
41      Brighton  1930158.00        158.70              12162.20

Task 3: Suburb-Level Feature Engineering

The ratio of average price to average building area was calculated for each suburb.

Steps:
• Grouped data by suburb
• Calculated average price and average building area
• Computed ratio = avg(price) / avg(buildingarea)

Missing values in buildingarea were handled using median to ensure accurate aggregation.

This metric helps compare property value relative to built-up space across suburbs.